services:
  postgres:
    image: postgres:17
    container_name: barkly-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: barkly_tp
      POSTGRES_DB: barkly
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
