services:
  postgres:
    image: postgres:17
    container_name: barkly-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: barkly_tp
      POSTGRES_DB: barkly
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./src/backend
    container_name: barkly-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: barkly_tp
      DB_NAME: barkly
    depends_on:
      - postgres

  frontend:
    build: ./src/public
    container_name: barkly-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata:


